version: 2

sources:
  - name: state_gov
    tables:
      - name: states_with_elections
        description: >
          States with regularly scheduled gubernatorial elections
      - nama: election_results_2020
        description: >
          2020 gubernatorial election results
      - nama: election_results_2018
        description: >
          2018 gubernatorial election results
      - nama: election_results_2016
        description: >
          2016 gubernatorial election results
      - nama: election_results_2014
        description: >
          2014 gubernatorial election results
      - nama: election_results_2012
        description: >
          2012 gubernatorial election results

  - name: political
    tables:
      - name: fips
        description: >
          FIPS codes for states and counties. 
          See https://www.census.gov/library/reference/code-lists/ansi.html
      - name: educational_attainment
        description: >
          Educational attainment estimates as provided by the Census. 
          See https://www.census.gov/topics/education/educational-attainment.html
      - name: income
        description: >
          Income estimates as provided by the Census Bureau. 
          See https://www.census.gov/topics/income-poverty/income.html
      - name: race
        description: >
          Race estimates as provided by the Census Bureau.
          See https://www.census.gov/topics/population/race.html
